In [1]:
import tensorflow as tf
print("TensorFlow version:", tf.__version__)


TensorFlow version: 2.10.1


In [2]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

In [3]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Conv2D(6, (5, 5), activation='relu', input_shape=(28, 28, 1)),
  tf.keras.layers.AveragePooling2D((2,2), strides=(2,2)),
  tf.keras.layers.Conv2D(16, (5,5), activation="relu"),
  tf.keras.layers.AveragePooling2D((2,2), strides=(2,2)),
  tf.keras.layers.Flatten(),
  tf.keras.layers.Dense(120, activation="relu"),
  tf.keras.layers.Dense(84, activation="relu"),
  tf.keras.layers.Dense(10, activation="softmax")
])

In [4]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

In [5]:
predictions = model(x_train[:1]).numpy()
predictions

array([[0.09951755, 0.09883981, 0.09829108, 0.10308765, 0.09896996,
        0.10039465, 0.09815952, 0.09874943, 0.0993045 , 0.10468588]],
      dtype=float32)

In [6]:
tf.nn.softmax(predictions).numpy()

array([[0.09995156, 0.09988383, 0.09982905, 0.10030903, 0.09989684,
        0.10003926, 0.09981591, 0.09987481, 0.09993026, 0.10046948]],
      dtype=float32)

In [7]:
tf.nn.softmax(predictions).numpy()

array([[0.09995156, 0.09988383, 0.09982905, 0.10030903, 0.09989684,
        0.10003926, 0.09981591, 0.09987481, 0.09993026, 0.10046948]],
      dtype=float32)

In [8]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [9]:
loss_fn(y_train[:1], predictions).numpy()

2.3021927

In [10]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [11]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5


c:\Users\Mark Andrey Rubio\miniconda3\envs\tf\lib\site-packages\keras\backend.py:5582: UserWarning: "`sparse_categorical_crossentropy` received `from_logits=True`, but the `output` argument was produced by a Softmax activation and thus does not represent logits. Was this intended?
  output, from_logits = _get_logits(


1875/1875 [==============================] - 7s 3ms/step - loss: 0.2353 - accuracy: 0.9273
Epoch 2/5
1875/1875 [==============================] - 6s 3ms/step - loss: 0.0779 - accuracy: 0.9752
Epoch 3/5
1875/1875 [==============================] - 6s 3ms/step - loss: 0.0573 - accuracy: 0.9814
Epoch 4/5
1875/1875 [==============================] - 6s 3ms/step - loss: 0.0455 - accuracy: 0.9860
Epoch 5/5
1875/1875 [==============================] - 6s 3ms/step - loss: 0.0370 - accuracy: 0.9881


In [12]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 1s - loss: 0.0381 - accuracy: 0.9876 - 1s/epoch - 4ms/step


[0.03812792897224426, 0.9876000285148621]